/* ==============================================
   ✨ AI Image Generator by 𝐃ᴇᴠ|𝐀ɴ𝐬ʜ𝐀ᴘɪ ✨
   Contact: @anshapi
   GitHub: github.com/Anshu-AI
   Created with ❤️ by 𝐃ᴇᴠ|𝐀ɴ𝐬ʜ𝐀ᴘɪ
   ============================================== */

import { serve } from "https://deno.land/std@0.203.0/http/server.ts";

const IMG_BB_API_KEY = 'b32ff9b073b75334477d3f1faf2bb2a5';
const DECOHERE_URL = 'https://www.decohere.ai/api/accountDetails?token=turbo';
const GENERATE_TURBO_URL = 'https://turbo.decohere.ai/generate/turbo';
const CREDIT_OWNER = '𝐃ᴇᴠ|𝐀ɴ𝐬ʜ𝐀ᴘɪ';
const CREDIT_CHANNEL = 'https://t.me/anshapi';

function generateSeed() {
    return Math.floor(Math.random() * 2147483647);
}

function getRandomUserAgent() {
    const userAgents = [
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/58.0.3029.110 Safari/537.3 [Powered by 𝐃ᴇᴠ|𝐀ɴ𝐬ʜ𝐀ᴘɪ]",
        "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 Chrome/59.0.3071.115 Safari/537.36 [Developer: 𝐃ᴇᴠ|𝐀ɴ𝐬ʜ𝐀ᴘɪ]",
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/60.0.3112.113 Safari/537.36 [AI by 𝐃ᴇᴠ|𝐀ɴ𝐬ʜ𝐀ᴘɪ]"
    ];
    return userAgents[Math.floor(Math.random() * userAgents.length)];
}

async function fetchTurboToken() {
    try {
        const res = await fetch(DECOHERE_URL, {
            headers: { "User-Agent": getRandomUserAgent() }
        });
        const data = await res.json();
        return data.turboToken || null;
    } catch {
        return null;
    }
}

async function fetchWithAuth(url, data, token) {
    const enhancedData = { ...data, _credit: CREDIT_OWNER, _channel: CREDIT_CHANNEL, _timestamp: Date.now() };
    const res = await fetch(url, {
        method: 'POST',
        headers: {
            "Content-Type": "application/json",
            "Authorization": `Bearer ${token}`,
            "User-Agent": getRandomUserAgent()
        },
        body: JSON.stringify(enhancedData)
    });
    const text = await res.text();
    return { http_code: res.status, response: text };
}

async function uploadToImgBB(base64Image) {
    try {
        const params = new URLSearchParams();
        params.append('key', IMG_BB_API_KEY);
        params.append('image', base64Image);
        const res = await fetch('https://api.imgbb.com/1/upload', {
            method: 'POST',
            headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
            body: params
        });
        const data = await res.json();
        return data.data?.url || null;
    } catch {
        return null;
    }
}

async function fetchAndDisplayImages(prompt, imageNumber, turboToken) {
    const seedValue = generateSeed();
    const imageUrls = {};
    for (let i = 0; i < imageNumber; i++) {
        const data = { prompt, seed: seedValue + i, width: 576, height: 1024, steps: 4, safety_filter: true, enhance: true, submission_time: Math.floor(Date.now()/1000), customer_id: "not_signed_in", _credit: `Generated by ${CREDIT_OWNER}` };
        const result = await fetchWithAuth(GENERATE_TURBO_URL, data, turboToken);
        if (result.http_code === 200) {
            try {
                const json = JSON.parse(result.response);
                const base64Image = json.image;
                if (base64Image) {
                    const url = await uploadToImgBB(base64Image);
                    imageUrls[`image_url_${i+1}`] = url;
                } else {
                    imageUrls[`image_url_${i+1}`] = null;
                }
            } catch {
                imageUrls[`image_url_${i+1}`] = null;
            }
        } else {
            imageUrls[`image_url_${i+1}`] = null;
        }
    }
    return imageUrls;
}

serve(async (req) => {
    const url = new URL(req.url);
    const prompt = url.searchParams.get('prompt');
    const imageNumber = parseInt(url.searchParams.get('image') || "0", 10);

    if (!prompt || !imageNumber || imageNumber < 1) {
        return new Response(JSON.stringify({ error: 'Invalid parameters', usage: '?prompt=TEXT&image=NUMBER', developer: CREDIT_OWNER, contact: CREDIT_CHANNEL }, null, 2), { status: 400, headers: { 'Content-Type': 'application/json' } });
    }

    try {
        const turboToken = await fetchTurboToken();
        if (!turboToken) return new Response(JSON.stringify({ error: 'Turbo token fetch failed', developer: CREDIT_OWNER, contact: CREDIT_CHANNEL }, null, 500), { status: 500, headers: { 'Content-Type': 'application/json' } });

        const images = await fetchAndDisplayImages(prompt, imageNumber, turboToken);
        return new Response(JSON.stringify({ ...images, metadata: { developer: CREDIT_OWNER, channel: CREDIT_CHANNEL, generated_at: new Date().toISOString() } }, null, 2), { status: 200, headers: { 'Content-Type': 'application/json' } });
    } catch (err) {
        return new Response(JSON.stringify({ error: 'Unexpected error', message: err.message, developer: CREDIT_OWNER, contact: CREDIT_CHANNEL, timestamp: new Date().toISOString() }, null, 2), { status: 500, headers: { 'Content-Type': 'application/json' } });
    }
});